# Generated by Django 4.2.2 on 2023-07-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_blog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='type',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
    ]
